In [5]:
# Write a code snippet to convert a string to a list.
str1 = "Analytics Vidhya"
print(str1.split(" "))

['Analytics']


In [7]:
# Write a code snippet to reverse a string.
str1 = "Analytics Vidhya"
str2 = ""
for i in str1:
    str2 = i + str2
print("The original string is: ", str1)
print("The reversed string is: ", str2)

ayhdiV scitylanA
The original string is:  Analytics Vidhya
The reversed string is:  ayhdiV scitylanA


In [3]:
#Write a code snippet to sort a list in Python.
my_list = [3, 2, 1]
my_list.sort()
print(my_list)

[1, 2, 3]


In [4]:
# What is the difference between mutable and immutable?
# Ans. Mutable objects: They can be updated once defined. e.g., list.
# Immutable objects: They cannot be updated. e.g., tuples.

In [5]:
#How can you delete a file in Python?
import os
os.remove("txt1.txt")

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'txt1.txt'

How to access an element of a list?
Ans. The element in a list can be accessed using list_name [index]. For instance:

Given a list [1, 2, 3, 4].

The indexing of the list starts from 0.

The first element of the list can be accessed using list[0], which will print element “1”.

The second element can be accessed using list[1] and so on.

In [6]:
# Discuss different ways of deleting an element from a list.
# Ans. There are two ways in which we can delete elements from the list:

# 1. By using the remove() function
# 2. By using the pop() function

# The remove () function deletes the mentioned element from the list.

list1 = [1, 2, 3, 4]
list1.remove(2)
print(list1)

# Pop() function delete element mentioned at a specific index from the list

list1.pop(1)
print(list1)

[1, 3, 4]
[1, 4]


In [8]:
# Write a code snippet to delete an entire list.
list1 = [1, 2, 3, 4]
list1.clear()
list1

[]

In [10]:
# Write a code snippet to reverse an array.

# 1. Using the flip() function
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.flip(arr1)
print(arr2)

# 2. Without using any function
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = arr1[::-1]
print(arr2)

[4 3 2 1]
[4 3 2 1]


In [14]:
# Write a code snippet to get an element, delete an element, and update an element in an array.

# Access: We can access an element of an array by using array_name[index].
# print(arr[index])

# Delete: We can delete the element of an array using the delete() function.
import numpy as np
arr2 = [1, 2, 3, 4]
x = np.delete(arr2, 0)
print(x)

# Update: We can update the element of an array using the below syntax:
# array_name[index] = element

[2 3 4]


In [20]:
# Write a code snippet to concatenate lists.
list1= ["w", "a", "w", "b"]
list2 = ["e", " ","riting","log"]
list3 = [x + y for x, y in zip(list1, list2)]
print(list3)

['we', 'a ', 'writing', 'blog']


In [21]:
# Write a code snippet to generate the square of every element of a list.
lst = [1, 2, 3, 4]
lst_final = []
for x in lst:
    lst_final.append(x * x)
print(lst_final)

[1, 4, 9, 16]


# What is the difference between range and xrange?
In Python 2, range() returns a list, and xrange() returns an iterator. But in Python 3 xrange() no longer exists while range() returns an iterator.

# What is pickling and unpickling in Python?
Ans. Pickling is converting a Python object (list, dict, function, etc.) to a byte stream(0s and 1s), and unpickling is converting the byte stream back to a python object. It is used to transfer and store various Python objects. We can use pickle or dill Python packages for this.

# What is init in Python?
Ans. __init__ method is used in Python to initialize the attributes of the object when the object is created. So, it is similar to the constructor in Java or C++. It is declared within the class as a reserved method.

# Which is faster, Python list or Numpy arrays, and why?
Ans. NumPy arrays are faster than Python lists for numerical operations.

NumPy is an open-source library for working with arrays in Python, and it provides a number of functions for performing operations on arrays efficiently.

They are faster than Python lists because they are implemented in C, while Python lists are implemented in Python. This means that operations on NumPy arrays are implemented in a compiled language, which makes them faster than operations on Python lists, which are implemented in an interpreted language.

Python also has an inbuilt array library for basic operations. W can use it as ‘import array as arr’

In [23]:
# Explain the top 5 functions used for Python strings.

# len(): This function returns the length of a string.
s = 'Hello, World!'
print(len(s))
# 13

# strip(): This function removes leading and trailing whitespace from a string.
s = '   Hello, World!   '
print(s.strip())
# ‘Hello, World!’

# replace(): This function replaces all occurrences of a specified string with another string.
s = 'Hello, World!'
print(s.replace('World', 'Universe'))
# ‘Hello, Universe!’

# split(): This function splits a string into a list of substrings based on a delimiter.
s = 'Hello, World!'
print(s.split(','))
# [‘Hello’, ‘ World!’]

# upper() and lower(): These functions convert a string to uppercase or lowercase, respectively.
s = 'Hello, World!'
print(s.upper())
# ‘HELLO, WORLD!’

print(s.lower())

13
Hello, World!
Hello, Universe!
['Hello', ' World!']
HELLO, WORLD!
hello, world!


# What is the use of the pass keyword in Python?
Ans. Pass is a null statement that does nothing. It is often used as a placeholder where a statement is required syntactically, but no action needs to be taken. For example, if you want to define a function or a class but haven’t yet decided what it should do, you can use the pass as a placeholder.